import re

# Diccionario de marcas con aliases (variantes de escritura)
BRAND_ALIASES = {
    "Samsung": ["samsung"],
    "LG": ["lg"],
    "Sony": ["sony"],
    "Xiaomi": ["xiaomi", "redmi", "mi"],
    "Apple": ["apple", "iphone"],
    "Motorola": ["motorola", "moto"],
    "Honor": ["honor"],
    "Oppo": ["oppo"],
    "Nokia": ["nokia"],
    "HP": ["hp", "hewlett packard"],
    "Lenovo": ["lenovo"],
    "Asus": ["asus"],
    "Acer": ["acer"],
    "MSI": ["msi"],
    "Dell": ["dell"],
    "Midea": ["midea"],
    "Midas": ["midas"],
    "Kolke": ["kolke"],
    "Peabody": ["peabody"],
    "Mondial": ["mondial"],
    "Tramontina": ["tramontina"],
    "Electrolux": ["electrolux"],
    "Whirlpool": ["whirlpool"],
    "Karcher": ["karcher", "kärcher"],
    "Michelin": ["michelin"],
    "Husqvarna": ["husqvarna"],
    "Ibanez": ["ibanez"],
    "Palmer": ["palmer"],
    "Remington": ["remington"],
    "Puma": ["puma"],
    "Nike": ["nike"],
    "New Balance": ["new balance"],
    "JBL": ["jbl"],
    "Philips": ["philips"],
    "Taiga": ["taiga"],
    "Benelli": ["benelli"],
    "Buler": ["buler"],
    "Caloi": ["caloi"],
    "Fama": ["fama"],
    "Goodweather": ["goodweather","goodweader"],
    "Xion": ["xion"],
    "Wasko": ["wasko"],
    "Abba": ["abba"],
    "Parana": ["parana"],
    "Koala": ["koala"],
    "Comfee": ["comfee"],
    "Tokyo": ["tokyo", "tokio"],
    "Bosch": ["bosch"],
    "Black+Decker": ["black decker", "black+decker", "black&decker"],
    "Makita": ["makita"],
    "DeWalt": ["dewalt"],
    "Stanley": ["stanley"],
    "Realme": ["realme"],
    "Gama": ["gama"],
    "Oster": ["oster"],
    "Atma": ["atma"],
    "Mabe": ["mabe"],
    "Daewoo": ["daewoo"],
    "Hyundai": ["hyundai"],
    "Kia": ["kia"],
    "Suzuki": ["suzuki"],
    "Yamaha": ["yamaha"],
    "Honda": ["honda"],
    "Playstation": ["playstation", "ps4", "ps5"],
    "Xbox": ["xbox"],
    "Nintendo": ["nintendo"],
    "Ftx": ["ftx"],
    "Babyliss": ["babyliss"],
    "Milano": ["milano"],
    "Rheem": ["rheem"],
    "Haustec": ["haustec"],
    "Crocs": ["crocs"],
    "Vans": ["vans"],
    "Converse": ["converse"],
    "Caterpillar": ["cat", "caterpillar"],
    "Asics": ["asics"],
    "Adidas": ["adidas"],
    "Kenton": ["kenton"],
    "Nogal": ["nogal"],
    "Ufesa": ["ufesa"],
    "Superspuma": ["superspuma"],
    "Sueñolar": ["sueñolar"],
    "Parana": ["parana"],
    "Consul": ["consul"],
    "Consumer": ["consumer"],
    "Corzus": ["corzus"],
    "Beko": ["beko"],
    "Aiwa": ["aiwa"],
    "Nappo": ["nappo"],
    "TCL": ["tcl"],
    "Hydrate": ["hydrate"],
    "Stihl": ["stihl"],
    "Under Armour": ["under armour", "underarmour"],
    "Bestway": ["bestway"],
    "Trapp": ["trapp"],
    "Arno": ["arno"],
    "Moulinex": ["moulinex"],
    "Abba": ["abba"],
    "Athletic": ["athletic"],
    "Jam": ["jam"],
    "Amazon": ["amazon"],
    "Havit": ["havit"],
    "darkFlash": ["darkflash"],
    "Redragon": ["redragon"],
    "Vonixx": ["vonixx"],
    "Kojima": ["kojima"],
    "VCP": ["vcp"],
    "KZ": ["kz"],
    "Ecopower": ["ecopower"],
    "Multigraph": ["multigraph"],
    "Xtech": ["xtech"],
    "TP-Link": ["tp-link","tplink","tp link"],
    "Kodak": ["kodak"],
    "Logitech": ["logitech"],
    "Steelseries": ["steelseries"],
    "Corsair": ["corsair"],
    "HyperX": ["hyperx"],
    "Kingston": ["kingston"],
    "Razer": ["razer"],
    "Toshiba": ["toshiba"],
    "Sate": ["sate","satellite"],
    "Quanta": ["quanta"],
    "Onikuma": ["onikuma"],
    "Keepdata": ["keepdata"],
    "LUO": ["luo"],
    "Tronsmart": ["tronsmart"],
    "AOC": ["aoc"],
    "Maxell": ["maxell"],
    "Hikvision": ["hikvision"],
    "Brother": ["brother"],
    "Gigabyte": ["gigabyte"],
    "ASRock": ["asrock"],
    "Biostar": ["biostar"],
    "Goline": ["goline"],
    "Afox": ["afox"],
    "STAR": ["star"],
    "Leopard": ["leopard"],
    "Thermalright": ["thermalright"],
    "EPSON": ["epson"],
    "Freeman": ["freeman"],
    "Aigo": ["aigo"],
    "Kenwood": ["kenwood"],
    "LTD": ["ltd"],
    "MB": ["mb"],
    "Pioneer": ["pioneer"],
    "Shamsonic": ["shamsonic"],
    "UPGAMER": ["upgamer"],
    "Aikon": ["aikon"],
    "Casio": ["casio"],
    "Split": ["split"],
    "AKG": ["akg"],
    "Speakon": ["speakon"],
}

def normalize_text(text: str) -> str:
    """
    Limpia el texto y lo deja en minúsculas sin espacios duplicados
    """
    return re.sub(r"\s+", " ", (text or "").strip()).lower()


def extract_brand(nombre: str) -> str:
    """
    Detecta la marca dentro del nombre del producto
    """
    if not nombre:
        return ""

    nombre_norm = normalize_text(nombre)

    for brand, aliases in BRAND_ALIASES.items():
        for alias in aliases:
            pattern = r"\b" + re.escape(alias.lower()) + r"\b"
            if re.search(pattern, nombre_norm):
                return brand

    return ""